import { readFile, writeFile, mkdir } from 'fs/promises';
import { existsSync } from 'fs';
import { join, resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { config } from 'dotenv';
import type { ComponentRecord, ComponentRegistry } from '../pipeline/types.js';
import { runLlm } from '../agents/test-gen/llm-runner.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export class SelectorsGenerator {
  async generate(registryPath: string, outputPath: string): Promise<void> {
    if (!existsSync(registryPath)) {
      console.log('[SelectorsGenerator] Registry not found:', registryPath);
      return;
    }

    const registry = JSON.parse(await readFile(registryPath, 'utf-8')) as ComponentRegistry;
    const components = Object.values(registry.components);
    if (components.length === 0) {
      console.log('[SelectorsGenerator] Registry is empty, skipping');
      return;
    }

    console.log(`[SelectorsGenerator] ${components.length} components → generating selectors.js…`);

    // Default: deterministic generation from registry (no LLM guessing).
    // Set SELECTORS_GEN_LLM=true to opt into LLM-based generation (legacy).
    if (process.env.SELECTORS_GEN_LLM !== 'true') {
      const out = this._generateDeterministic(registry);
      await mkdir(dirname(outputPath), { recursive: true });
      await writeFile(outputPath, out, 'utf-8');
      console.log('[SelectorsGenerator] Written (deterministic):', outputPath);
      return;
    }

    const fileContent = await this._generateViaLlm(registry);

    await mkdir(dirname(outputPath), { recursive: true });
    await writeFile(outputPath, fileContent, 'utf-8');
    console.log('[SelectorsGenerator] Written:', outputPath);
  }

  private _buildLlmPromptIntro(registry: ComponentRegistry): string {
    return `You are generating a cypress/support/selectors.js file from a component registry.
Output ONLY raw JavaScript — no markdown, no code fences, no backticks, no explanation.
The very first character of your output must be "/" (the start of a JS comment).

REGISTRY:
${JSON.stringify(registry, null, 2)}

GENERATION RULES:
1. Group components by page. Page namespace key = UPPER_SNAKE_CASE of the page path slug.
   Examples: "/v1/login" → V1_LOGIN, "/member-hr/home" → MEMBER_HR_HOME, "/" → HOME
2. Constant name inside each group = UPPER_SNAKE_CASE derived from component LABEL (not ID).
   Example: label "Finance tab" → FINANCE_TAB, label "Sign in" → SIGN_IN
3. Components with pages.length > 2 → place in GLOBAL group
4. Add a // confidence: <level> comment when confidence is not "high"
5. Header comment must include the generation timestamp`;
  }

  private _buildLlmPromptSelectorRules(): string {
    return `SELECTOR CONVERSION (critical — Cypress uses CSS, not Playwright ARIA locators):
The registry may contain Playwright-style ARIA locators in selectors.aria and selectors.preferred.
These DO NOT work with cy.get() in Cypress. Convert them using this priority:

Priority 1 — use selectors.testid if present:  [data-testid="X"] or [data-cy="X"]
Priority 2 — use selectors.css if present:       the raw CSS string as-is
Priority 3 — use selectors.preferred if it starts with "[data-": the raw string as-is
Priority 4 — convert ARIA locator to CSS equivalent:
  - button[name="X"]   → button:contains("X")   or  [aria-label="X"]
  - link[name="X"]     → a:contains("X")         or  a[aria-label="X"]
  - textbox[name="X"]  → input[aria-label="X"]   (NEVER input[name="X"] — ARIA name is not the HTML name attribute)
  - tab[name="X"]      → [role="tab"]:contains("X")
  - menuitem[name="X"] → [role="menuitem"]:contains("X")
  - option[name="X"]   → [role="option"]:contains("X")
  - row[name="X"]      → [role="row"]:contains("X")
  - gridcell[name="X"] → [role="gridcell"]:contains("X")
  - generic[name="X"]  → [aria-label="X"]

FORBIDDEN:
- Any selector in the format role[name="X"] — this is Playwright ARIA syntax, not CSS
- Markdown code fences`;
  }

  private _buildLlmPromptOutputFormat(): string {
    return `Expected output format:
// AUTOGENERATED — do not edit manually
// Source: registry/components.json
// Last updated: ${new Date().toISOString()}
//
// To update: edit registry/components.json and run npm run generate:selectors

export const SELECTORS = {
  // Page: /v1/login
  V1_LOGIN: {
    EMAIL_INPUT: '[data-ref="e7"]',
    PASSWORD: 'input[aria-label="Password"]',
    SIGN_IN: 'button:contains("Sign in")',
  },

  GLOBAL: {
    LOADING_SPINNER: '[data-testid="loading-spinner"]',
    ERROR_TOAST: '[role="alert"]',
  },
};

CRITICAL: Your response must start directly with // and contain only valid JavaScript.
Do NOT wrap output in \`\`\`javascript...\`\`\` or any other markdown.`;
  }

  private _buildLlmPrompt(registry: ComponentRegistry): string {
    return [
      this._buildLlmPromptIntro(registry),
      this._buildLlmPromptSelectorRules(),
      this._buildLlmPromptOutputFormat(),
    ].join('\n\n');
  }

  private async _generateViaLlm(registry: ComponentRegistry): Promise<string> {
    const prompt = this._buildLlmPrompt(registry);
    try {
      const fileContent = (await runLlm(prompt))
        .replace(/^```(?:javascript|js)?\s*\n?/i, '')
        .replace(/\n?```\s*$/i, '')
        .trim();
      if (!fileContent.includes('SELECTORS')) {
        throw new Error('Response does not contain SELECTORS — falling back');
      }
      return fileContent;
    } catch (err) {
      console.warn('[SelectorsGenerator] Claude failed, using deterministic fallback:', (err as Error).message);
      return this._generateDeterministic(registry);
    }
  }

  private _groupComponents(components: ComponentRecord[]): {
    byPage: Record<string, ComponentRecord[]>;
    global: ComponentRecord[];
  } {
    const byPage: Record<string, ComponentRecord[]> = {};
    const global: ComponentRecord[] = [];

    for (const comp of components) {
      if (comp.pages.length > 2) {
        global.push(comp);
        continue;
      }
      for (const page of comp.pages) {
        const key = this._pageKey(page);
        (byPage[key] ??= []).push(comp);
      }
    }

    return { byPage, global };
  }

  private _fileHeaderLines(): string[] {
    return [
      '// AUTOGENERATED — do not edit manually',
      '// Source: registry/components.json',
      `// Last updated: ${new Date().toISOString()}`,
      '//',
      '// To update: edit registry/components.json and run npm run generate:selectors',
      '',
    ];
  }

  private _renderComponentLines(comps: ComponentRecord[]): string[] {
    return comps.map((comp) => {
      const constName = this._toUpperSnake(comp.label);
      const comment = comp.confidence !== 'high' ? `  // confidence: ${comp.confidence}` : '';
      return `    ${constName}: ${JSON.stringify(this._bestSelector(comp.selectors))},${comment}`;
    });
  }

  private _generateDeterministic(registry: ComponentRegistry): string {
    const components = Object.values(registry.components);
    const { byPage, global } = this._groupComponents(components);

    const lines: string[] = [...this._fileHeaderLines(), 'export const SELECTORS = {'];

    for (const [pageKey, comps] of Object.entries(byPage)) {
      lines.push(`  // Page: /${pageKey.toLowerCase()}`);
      lines.push(`  ${pageKey}: {`, ...this._renderComponentLines(comps), '  },', '');
    }

    if (global.length > 0) {
      lines.push('  // Global (appears on 3+ pages)', '  GLOBAL: {', ...this._renderComponentLines(global), '  },');
    }

    lines.push('};');
    return lines.join('\n') + '\n';
  }

  private _bestSelector(selectors: ComponentRecord['selectors']): string {
    // Historic note: `selectors.testid` already stores the full CSS
    // (`[data-testid="X"]`), not the bare id — don't wrap it again.
    if (selectors.testid) {
      return selectors.testid.startsWith('[data-')
        ? selectors.testid
        : `[data-testid="${selectors.testid}"]`;
    }
    if (selectors.css) return selectors.css;
    if (selectors.preferred?.startsWith('[data-')) return selectors.preferred;
    return selectors.preferred;
  }

  private _pageKey(page: string): string {
    const slug = page.replace(/^\//, '') || 'home';
    return this._toUpperSnake(slug);
  }

  private _toUpperSnake(str: string): string {
    return str
      .replace(/[^a-zA-Z0-9]+/g, '_')
      .replace(/^_|_$/g, '')
      .toUpperCase() || 'UNKNOWN';
  }
}

// ─── CLI ──────────────────────────────────────────────────────────────────────

const isMain = process.argv[1]?.replace(/\\/g, '/') === __filename.replace(/\\/g, '/');
if (isMain) {
  config({ path: resolve(__dirname, '..', '..', '.env') });

  const dataDir = resolve(__dirname, '..', '..', 'data');
  const cypressDir = resolve(__dirname, '..', '..', 'cypress-tests');
  const registryPath = join(dataDir, 'registry', 'components.json');
  const outputPath = join(cypressDir, 'cypress', 'support', 'selectors.js');

  console.log('[SelectorsGenerator] Registry:', registryPath);
  console.log('[SelectorsGenerator] Output:  ', outputPath, '\n');

  await new SelectorsGenerator().generate(registryPath, outputPath);
}
