// AUTOGENERATED — do not edit manually
// Source: registry/components.json
// Last updated: 2026-05-26T18:21:34.517Z
//
// To update: edit registry/components.json and run npm run generate:selectors

export const SELECTORS = {
  // Page: /v1_login
  V1_LOGIN: {
    EMAIL: "[data-testid=\"login-email-input\"]",
    PASSWORD: "[data-testid=\"login-password-input\"]",
    SIGN_IN: "[data-testid=\"login-submit-btn\"]",
  },

};
